---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations: {}
  labels:
    app: "MySQL-Database-service"
  name: "MySQL-Database-service"
spec:
  ports:
  - name: "mysql-dbms"
    port: 3306
  selector:
    app: "MySQL-Database"
  type: "NodePort"

