---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations: {}
  labels:
    app: "PetClinic-service"
  name: "PetClinic-service"
spec:
  ports:
  - name: "tomcat"
    port: 8080
  selector:
    app: "PetClinic"
  type: "NodePort"

